# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a79acd79906cdf2a2f576a8396e66122459a2808cb52d805e3117b1d622b2abcdd5455a74bf177167f2339b8055177be6d035221a0d838e3464a4e5bdff6e597

test:
  secret_key_base: 862d696aad6ecf00ddea1774b3ef4702a3484a953a1c1991d0efdada0971e22c5818042296244e99c5a06c9cdba680fa816b37f8feb3987ba0b1f49600cb835f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
